import type { IbkrDeviceEnrollment, IbkrSyncDevice } from '@/lib/types';

const DAY = 86_400_000;
const HOUR = 3_600_000;

/** Singapore has no daylight-saving transition; the worker uses the same daily boundary. */
export function backgroundSyncStatus(device: IbkrSyncDevice, now = Date.now()) {
  if (device.lastStatus === 'failed' || device.lastError)
    return { label: 'Sync needs attention', attention: true };
  if (device.lastStatus === 'running') {
    const elapsed = now - Date.parse(device.lastSeenAt ?? device.createdAt);
    return elapsed > 15 * 60_000
      ? { label: 'Sync needs attention', attention: true }
      : { label: 'Sync in progress', attention: false };
  }
  if (device.blocked) return { label: 'Sync needs attention', attention: true };
  let due = Math.floor((now + 8 * HOUR) / DAY) * DAY - 2 * HOUR;
  if (due > now) due -= DAY;
  if (
    now >= due + HOUR &&
    Date.parse(device.createdAt) < due &&
    Date.parse(device.lastVerifiedAt ?? device.createdAt) < due
  )
    return { label: 'Daily sync overdue', attention: true };
  return device.lastVerifiedAt
    ? { label: 'Synced and verified', attention: false }
    : { label: `Waiting for ${device.name}`, attention: false };
}

/** Only public enrollment fields may leave the setup form; server verifies the proof. */
export function parsePublicEnrollment(text: string): IbkrDeviceEnrollment {
  const message = 'Paste only the public connection details generated by your Mac setup.';
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    throw new Error(message);
  }
  const fields = [
    'version',
    'deviceId',
    'cashPositionId',
    'name',
    'publicKey',
    'connectorFingerprint',
    'audience',
    'createdAt',
    'signature',
  ];
  if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error(message);
  const data = value as Record<string, unknown>;
  if (
    Object.keys(data).length !== fields.length ||
    Object.keys(data).some((key) => !fields.includes(key)) ||
    data.version !== 1 ||
    fields.slice(1).some((key) => typeof data[key] !== 'string' || !data[key]) ||
    (data.name as string).length > 80 ||
    (data.cashPositionId as string).length > 100 ||
    (data.publicKey as string).length > 200 ||
    (data.signature as string).length > 200 ||
    !/^[a-f0-9]{64}$/.test(data.connectorFingerprint as string)
  )
    throw new Error(message);
  return data as unknown as IbkrDeviceEnrollment;
}
